name: Check - BackEnd

on:
  pull_request:

env:
  IMAGE_NAME: justdab:0.0.1

jobs:
  publish-registry:
    strategy:
      matrix:
        name: [Java21]
        include:
          - name: Java21
            os: ubuntu-latest
            java-version: 21
    runs-on: ${{ matrix.os }}

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Clone Project
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
